### ISSUE TITLE
should we scatter implemented interface method everywhere in our code base?

### ISSUE THREAD

**Issue by FanchTheSystem** [libre-informatique/EcommerceBundle#19]
As example

In this file from our Ecommerce Bundle:
https://github.com/libre-informatique/EcommerceBundle/blob/master/src/Entity/OuterExtension/LibrinfoCRMBundle/AddressExtensionInterface.php

We need to imlement the Sylius interface : Sylius\Component\Core\Model\AddressInterface

This is done in at least two distinct file :
https://github.com/libre-informatique/EcommerceBundle/blob/master/src/Entity/OuterExtension/LibrinfoCRMBundle/AddressExtension.php (Only for some method)
https://github.com/libre-informatique/CRMBundle/blob/master/src/Entity/Address.php (Other Method)

1) so when Sylius interface change, we have impact on several source code, not always in the same repository 
2) it look like there is a cyclic dependency (Ecommerce need CRM need Ecommerce...)

**Comment by GlennCavarle** [comment]
This issue was also partially mentioned in the CRMBundle : https://github.com/libre-informatique/CRMBundle/issues/16

**Comment by FanchTheSystem** [comment]
About https://github.com/libre-informatique/CRMBundle/blob/master/src/Entity/Address.php there is also:
 Librinfo\CRMBundle\Entity\Address::setUpdatedAt (for Sylius\Component\Resource\Model\TimestampableInterface)
Implemented here:
https://github.com/blast-project/BaseEntitiesBundle/blob/master/src/Entity/Traits/Timestampable.php

And it look like there is the same kind of issue for Organism:
https://github.com/libre-informatique/CRMBundle/blob/master/src/Entity/Organism.php
